# Generated by Django 3.1.7 on 2021-02-24 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(max_length=10)),
                ('site_name', models.CharField(max_length=20)),
                ('home_page', models.CharField(max_length=20)),
                ('news', models.CharField(max_length=20)),
                ('about_us', models.CharField(max_length=20)),
                ('contact_us', models.CharField(max_length=20)),
                ('lang_switch', models.CharField(max_length=20)),
            ],
        ),
    ]
