# Generated by Django 3.1.7 on 2021-02-24 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('just_a_menu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='_id',
        ),
    ]
